dist: trusty
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - fuse
    - libfuse-dev
    - g++-7
    - gcc-7
env:
  - BAZEL_V=0.17.1
before_install:
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_V}/bazel-${BAZEL_V}-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh
  - export PATH=$HOME/bin:$PATH
  - export CC=gcc-7
  - echo "$GCS_KEY" | base64 -d > "$HOME"/gcs.key
script:
  - bazel build client:cloudrun-fs --verbose_failures --spawn_strategy=standalone --genrule_strategy=standalone --curses=no --jobs=4 --remote_http_cache=https://storage.googleapis.com/cloudrun-bazel --google_credentials="$HOME"/gcs.key
