dist: trusty
language: cpp

env:
  - BAZEL_V=0.17.1
before_install:
  - wget -O install.sh "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_V}/bazel-${BAZEL_V}-installer-linux-x86_64.sh"
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - bin/bazel build client:cloudrun-fs --verbose_failures --spawn_strategy=standalone --genrule_strategy=standalone
